In [2]:
# Matrix/Vector Constructors
import numpy as np

objDict = {}
# Matrix 1x3 / Vector as a row
v0 = np.array([1,2,3])
objDict['Row vector'] = v0

# Matrix 3x1 / Vector as a column
v1 = np.array([[1],[2],[3]])
objDict['Column vector'] = v1

# Matrix 2x3
M0 = np.array([[1,2,3],[4,5,6]])
objDict['A matrix'] = M0

# Identity matrix
M1 = np.identity(3)
objDict['Identity matrix']  = M1

# Ones matrix
M2 = np.ones((3,2), dtype = np.int32)
objDict['A matrix filled with ones'] = M2

# Zeros matrix
M3 = np.zeros((3,2), dtype = np.int32)
objDict['A matrix filled with zeros'] = M3

# Random (uniform distribution) matrix - float numbers in [0, 1)
M4 = np.random.rand(3,3)
objDict['A matrix filled with random float numbers'] = M4

# Random (uniform distribution) matrix - integer numbers in [low, high]
M5 = np.random.randint(-10, 10, size = (3,3))
objDict['A matrix filled with random int numbers'] = M5

# Display
for key, obj in objDict.items():
    print('{0:s} {1:s}:\n{2:s}\n'.format(key, str(np.shape(obj)), str(obj)))


Row vector (3,):
[1 2 3]

Column vector (3, 1):
[[1]
 [2]
 [3]]

A matrix (2, 3):
[[1 2 3]
 [4 5 6]]

Identity matrix (3, 3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A matrix filled with ones (3, 2):
[[1 1]
 [1 1]
 [1 1]]

A matrix filled with zeros (3, 2):
[[0 0]
 [0 0]
 [0 0]]

A matrix filled with random float numbers (3, 3):
[[0.6155961  0.10490414 0.00122874]
 [0.09284758 0.42754777 0.16616432]
 [0.50248859 0.74139382 0.46598431]]

A matrix filled with random int numbers (3, 3):
[[ 2  9 -2]
 [-6  2  3]
 [-5  2  8]]



In [3]:
# Matrix + scalar
M5 + 1

array([[ 3, 10, -1],
       [-5,  3,  4],
       [-4,  3,  9]])

In [4]:
# Min & Max
min_max = {}
min_max['Min of M5'] = np.min(M5)
min_max['Min of each row of M5'] = np.min(M5, axis = 1)
min_max['Min of each column of M5'] = np.min(M5, axis = 0)
min_max['Max of M5'] = np.max(M5)
min_max['Max of each row of M5'] = np.max(M5, axis = 1)
min_max['Max of each column of M5'] = np.max(M5, axis = 0)

print('M5:\n{0:s}\n'.format(str(M5)))
for key, value in min_max.items():
    print('{0:s}: {1:s}\n'.format(key, str(value)))

M5:
[[ 2  9 -2]
 [-6  2  3]
 [-5  2  8]]

Min of M5: -6

Min of each row of M5: [-2 -6 -5]

Min of each column of M5: [-6  2 -2]

Max of M5: 9

Max of each row of M5: [9 3 8]

Max of each column of M5: [2 9 8]



In [5]:
# Mean & Var & Std Var
mean_var = {}
mean_var['Mean of M5'] = np.mean(M5)
mean_var['Mean of each row of M5'] = np.mean(M5, axis = 1)
mean_var['Mean of each column of M5'] = np.mean(M5, axis = 0)

mean_var['Var of M5'] = np.var(M5)
mean_var['Var of each row of M5'] = np.var(M5, axis = 1)
mean_var['Var of each column of M5'] = np.var(M5, axis = 0)

mean_var['Std. Var of M5'] = np.std(M5)
mean_var['Std. Var of each row of M5'] = np.std(M5, axis = 1)
mean_var['Std. Var of each column of M5'] = np.std(M5, axis = 0)

print('M5:\n{0:s}\n'.format(str(M5)))
for key, value in mean_var.items():
    print('{0:s}: {1:s}\n'.format(key, str(value)))

M5:
[[ 2  9 -2]
 [-6  2  3]
 [-5  2  8]]

Mean of M5: 1.4444444444444444

Mean of each row of M5: [ 3.         -0.33333333  1.66666667]

Mean of each column of M5: [-3.          4.33333333  3.        ]

Var of M5: 23.580246913580247

Var of each row of M5: [20.66666667 16.22222222 28.22222222]

Var of each column of M5: [12.66666667 10.88888889 16.66666667]

Std. Var of M5: 4.855949640758257

Std. Var of each row of M5: [4.54606057 4.02768199 5.31245915]

Std. Var of each column of M5: [3.55902608 3.29983165 4.0824829 ]



In [13]:
reshape_dict = {}
M6 = M4.copy()
M6 = M6.reshape(1,-1)
reshape_dict['Reshaped view of M4'] = M6

# M7 & M8 & M9 will point to the same memory region
M7 = np.random.randint(-10, 10, size = (4,3))
reshape_dict['New integer matrix'] = M7
M8 = M7.reshape(2, -1)
reshape_dict['M7 - Reshaped (2, -1)'] = M8
M9 = M7.reshape(12)
reshape_dict['M7 - Reshaped (1, 5)'] = M9

for key, value in reshape_dict.items():
    print('{0:s}: {1:s}\n'.format(key, str(value)))

Reshaped view of M4: [[ 0.6155961   0.10490414 10.          0.09284758  0.42754777  0.16616432
   0.50248859  0.74139382  0.46598431]]

New integer matrix: [[ -4   1   2]
 [  4 -10  -9]
 [  9   6   0]
 [  7   8   8]]

M7 - Reshaped (2, -1): [[ -4   1   2   4 -10  -9]
 [  9   6   0   7   8   8]]

M7 - Reshaped (1, 5): [ -4   1   2   4 -10  -9   9   6   0   7   8   8]

