In [23]:
# Matrix/Vector Constructors
import numpy as np

objDict = {}
# Matrix 1x3 / Vector as a row
v0 = np.array([1,2,3])
objDict['Row vector'] = v0

# Matrix 3x1 / Vector as a column
v1 = np.array([[1],[2],[3]])
objDict['Column vector'] = v1

# Matrix 2x3
M0 = np.array([[1,2,3],[4,5,6]])
objDict['A matrix'] = M0

# Identity matrix
M1 = np.identity(3)
objDict['Identity matrix']  = M1

# Ones matrix
M2 = np.ones((3,2), dtype = np.int32)
objDict['A matrix filled with ones'] = M2

# Zeros matrix
M3 = np.zeros((3,2), dtype = np.int32)
objDict['A matrix filled with zeros'] = M3

# Random (uniform distribution) matrix - float numbers in [0, 1)
M4 = np.random.rand(3,3)
objDict['A matrix filled with random float numbers'] = M4

# Random (uniform distribution) matrix - integer numbers in [low, high]
M5 = np.random.randint(-10, 10, size = (3,3))
objDict['A matrix filled with random int numbers'] = M5

# Display
for key, obj in objDict.items():
    print('{0:s} {1:s}:\n{2:s}\n'.format(key, str(np.shape(obj)), str(obj)))


Row vector (3,):
[1 2 3]

Column vector (3, 1):
[[1]
 [2]
 [3]]

A matrix (2, 3):
[[1 2 3]
 [4 5 6]]

Identity matrix (3, 3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A matrix filled with ones (3, 2):
[[1 1]
 [1 1]
 [1 1]]

A matrix filled with zeros (3, 2):
[[0 0]
 [0 0]
 [0 0]]

A matrix filled with random float numbers (3, 3):
[[0.60681833 0.05415202 0.11658929]
 [0.82881748 0.7000841  0.6312773 ]
 [0.19767968 0.57007708 0.81640595]]

A matrix filled with random int numbers (3, 3):
[[ 4  3 -5]
 [ 2  8 -6]
 [-6  6 -6]]



In [24]:
# Matrix + scalar
M5 + 1

array([[ 5,  4, -4],
       [ 3,  9, -5],
       [-5,  7, -5]])

In [36]:
# Min & Max
min_max = {}
min_max['Min of M5'] = np.min(M5)
min_max['Min of each row of M5'] = np.min(M5, axis = 1)
min_max['Min of each column of M5'] = np.min(M5, axis = 0)
min_max['Max of M5'] = np.max(M5)
min_max['Max of each row of M5'] = np.max(M5, axis = 1)
min_max['Max of each column of M5'] = np.max(M5, axis = 0)

print('M5:\n{0:s}\n'.format(str(M5)))
for key, value in min_max.items():
    print('{0:s}: {1:s}\n'.format(key, str(value)))

M5:
[[ 4  3 -5]
 [ 2  8 -6]
 [-6  6 -6]]

Min of M5: -6

Max of M5: 8

Min of each row of M5: [-5 -6 -6]

Max of each row of M5: [4 8 6]

Min of each column of M5: [-6  3 -6]

Max of each column of M5: [ 4  8 -5]



In [37]:
# Mean & Var & Std Var
mean_var = {}
mean_var['Mean of M5'] = np.mean(M5)
mean_var['Mean of each row of M5'] = np.mean(M5, axis = 1)
mean_var['Mean of each column of M5'] = np.mean(M5, axis = 0)

mean_var['Var of M5'] = np.var(M5)
mean_var['Var of each row of M5'] = np.var(M5, axis = 1)
mean_var['Var of each column of M5'] = np.var(M5, axis = 0)

mean_var['Std. Var of M5'] = np.std(M5)
mean_var['Std. Var of each row of M5'] = np.std(M5, axis = 1)
mean_var['Std. Var of each column of M5'] = np.std(M5, axis = 0)

print('M5:\n{0:s}\n'.format(str(M5)))
for key, value in mean_var.items():
    print('{0:s}: {1:s}\n'.format(key, str(value)))

M5:
[[ 4  3 -5]
 [ 2  8 -6]
 [-6  6 -6]]

Mean of M5: 0.0

Mean of each row of M5: [ 0.66666667  1.33333333 -2.        ]

Mean of each column of M5: [ 0.          5.66666667 -5.66666667]

Var of M5: 29.11111111111111

Var of each row of M5: [16.22222222 32.88888889 32.        ]

Var of each column of M5: [18.66666667  4.22222222  0.22222222]

Std. Var of M5: 5.395471352079548

Std. Var of each row of M5: [4.02768199 5.73488351 5.65685425]

Std. Var of each column of M5: [4.3204938  2.05480467 0.47140452]

