In [2]:
# Matrix/Vector Constructors
import numpy as np

objDict = {}
# Matrix 1x3 / Vector as a row
v0 = np.array([1,2,3])
objDict['Row vector'] = v0

# Matrix 3x1 / Vector as a column
v1 = np.array([[1],[2],[3]])
objDict['Column vector'] = v1

# Matrix 2x3
M0 = np.array([[1,2,3],[4,5,6]])
objDict['A matrix'] = M0

# Identity matrix
M1 = np.identity(3)
objDict['Identity matrix']  = M1

# Ones matrix
M2 = np.ones((3,2), dtype = np.int32)
objDict['A matrix filled with ones'] = M2

# Zeros matrix
M3 = np.zeros((3,2), dtype = np.int32)
objDict['A matrix filled with zeros'] = M3

# Random (uniform distribution) matrix - float numbers in [0, 1)
M4 = np.random.rand(3,3)
objDict['A matrix filled with random float numbers'] = M4

# Random (uniform distribution) matrix - integer numbers in [low, high]
M5 = np.random.randint(-10, 10, size = (3,3))
objDict['A matrix filled with random int numbers'] = M5

# Display
for key, obj in objDict.items():
    print('{0:s} {1:s}:\n{2:s}\n'.format(key, str(np.shape(obj)), str(obj)))


Row vector (3,):
[1 2 3]

Column vector (3, 1):
[[1]
 [2]
 [3]]

A matrix (2, 3):
[[1 2 3]
 [4 5 6]]

Identity matrix (3, 3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A matrix filled with ones (3, 2):
[[1 1]
 [1 1]
 [1 1]]

A matrix filled with zeros (3, 2):
[[0 0]
 [0 0]
 [0 0]]

A matrix filled with random float numbers (3, 3):
[[0.07452231 0.4911985  0.49255716]
 [0.86381464 0.60278993 0.83816419]
 [0.79252262 0.86060273 0.4953053 ]]

A matrix filled with random int numbers (3, 3):
[[-2  5  2]
 [ 5 -8  1]
 [ 1 -1 -4]]



In [3]:
# Matrix + scalar
M5 + 1

array([[-1,  6,  3],
       [ 6, -7,  2],
       [ 2,  0, -3]])

In [4]:
# Min & Max
min_max = {}
min_max['Min of M5'] = np.min(M5)
min_max['Min of each row of M5'] = np.min(M5, axis = 1)
min_max['Min of each column of M5'] = np.min(M5, axis = 0)
min_max['Max of M5'] = np.max(M5)
min_max['Max of each row of M5'] = np.max(M5, axis = 1)
min_max['Max of each column of M5'] = np.max(M5, axis = 0)

print('M5:\n{0:s}\n'.format(str(M5)))
for key, value in min_max.items():
    print('{0:s}: {1:s}\n'.format(key, str(value)))

M5:
[[-2  5  2]
 [ 5 -8  1]
 [ 1 -1 -4]]

Min of M5: -8

Min of each row of M5: [-2 -8 -4]

Min of each column of M5: [-2 -8 -4]

Max of M5: 5

Max of each row of M5: [5 5 1]

Max of each column of M5: [5 5 2]



In [5]:
# Mean & Var & Std Var
mean_var = {}
mean_var['Mean of M5'] = np.mean(M5)
mean_var['Mean of each row of M5'] = np.mean(M5, axis = 1)
mean_var['Mean of each column of M5'] = np.mean(M5, axis = 0)

mean_var['Var of M5'] = np.var(M5)
mean_var['Var of each row of M5'] = np.var(M5, axis = 1)
mean_var['Var of each column of M5'] = np.var(M5, axis = 0)

mean_var['Std. Var of M5'] = np.std(M5)
mean_var['Std. Var of each row of M5'] = np.std(M5, axis = 1)
mean_var['Std. Var of each column of M5'] = np.std(M5, axis = 0)

print('M5:\n{0:s}\n'.format(str(M5)))
for key, value in mean_var.items():
    print('{0:s}: {1:s}\n'.format(key, str(value)))

M5:
[[-2  5  2]
 [ 5 -8  1]
 [ 1 -1 -4]]

Mean of M5: -0.1111111111111111

Mean of each row of M5: [ 1.66666667 -0.66666667 -1.33333333]

Mean of each column of M5: [ 1.33333333 -1.33333333 -0.33333333]

Var of M5: 15.654320987654321

Var of each row of M5: [ 8.22222222 29.55555556  4.22222222]

Var of each column of M5: [ 8.22222222 28.22222222  6.88888889]

Std. Var of M5: 3.956554181058857

Std. Var of each row of M5: [2.86744176 5.43650214 2.05480467]

Std. Var of each column of M5: [2.86744176 5.31245915 2.62466929]



In [6]:
# Reshape
reshape_dict = {}
M6 = M4.copy()
M6 = M6.reshape(1,-1)
reshape_dict['Reshaped view of M4'] = M6

# M7 & M8 & M9 will point to the same memory region
M7 = np.random.randint(-10, 10, size = (4,3))
reshape_dict['New integer matrix'] = M7
M8 = M7.reshape(2, -1)
reshape_dict['M7 - Reshaped (2, -1)'] = M8
M9 = M7.reshape(12)
reshape_dict['M7 - Reshaped (1, 5)'] = M9

for key, value in reshape_dict.items():
    print('{0:s}: {1:s}\n'.format(key, str(value)))

Reshaped view of M4: [[0.07452231 0.4911985  0.49255716 0.86381464 0.60278993 0.83816419
  0.79252262 0.86060273 0.4953053 ]]

New integer matrix: [[ 3 -5 -4]
 [-8 -3  8]
 [-7  6  3]
 [ 5 -2  0]]

M7 - Reshaped (2, -1): [[ 3 -5 -4 -8 -3  8]
 [-7  6  3  5 -2  0]]

M7 - Reshaped (1, 5): [ 3 -5 -4 -8 -3  8 -7  6  3  5 -2  0]



In [12]:
# Transpose
transpose = {}
M10 = M7.T
transpose['Transpose of a matrix'] = M10
v2 = np.array([1,2,3]).T
transpose['A pure-vector/one-dimensional array cannot be transposed'] = v2
v3 = np.array([[1,2,3]]).T
transpose['Transpose of a vector-like matrix'] = v3

for key, value in transpose.items():
    print('{0:s}:\n{1:s}\n'.format(key, str(value)))

Transpose of a matrix:
[[ 3 -8 -7  5]
 [-5 -3  6 -2]
 [-4  8  3  0]]

A pure-vector/one-dimensional array cannot be transposed:
[1 2 3]

Transpose of a vector-like matrix:
[[1]
 [2]
 [3]]



In [13]:
# Flatten
M11 = M7.flatten()
print('Flattening a matrix:\n{0:s}\n'.format(str(M11)))

Flattening a matrix:
[ 3 -5 -4 -8 -3  8 -7  6  3  5 -2  0]



In [21]:
# Rank
r = np.linalg.matrix_rank(M5)

# Determinant
det = np.linalg.det(M5)

print('Matrix: \n{0:s}\n+ Rank: {1:d}\n+ Determinant: {2:f}\n'.format(str(M5), r, det))

Matrix: 
[[-2  5  2]
 [ 5 -8  1]
 [ 1 -1 -4]]
+ Rank: 3
+ Determinant: 45.000000

